Added Support to Audit Launch Template resource
inspec/inspec-aws pull request #327
Opened 2021-04-21 05:19 UTC by Nirbhay1997

Signed-off-by: nirbhay <nkumar@chef.io>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-05-06 22:24 UTC, IanMadd commented on docs/resources/aws_ec2_launch_templates.md
> +One of either the launch_templates_name or launch_templates_id must be be provided.
Is it launch_templates_name or launch_template_names?
Same question with launch_templates_id.

2021-05-10 03:42 UTC, sathish-progress commented on libraries/aws_ec2_launch_template.rb
> +  example "describe aws_ec2_launch_template(launch_template_name: ['nirbhay-test-launch-temlate') do
typo!

` ['nirbh`

2021-05-10 03:49 UTC, sathish-progress commented on libraries/aws_ec2_launch_templates.rb
> +      return [] if !@api_response || @api_response.empty?
this conditional should return `launch_template_rows`, otherwise `fetch_data` would return an empty array on the second or any other consecutive loop

2021-05-10 03:50 UTC, sathish-progress commented on libraries/aws_ec2_launch_templates.rb
> +                            launch_template_tagsname: launch_template_tags['Name'],
is this a typo?
```suggestion
                            launch_template_tags_name: launch_template_tags['Name'],
```

2021-05-10 03:51 UTC, sathish-progress commented on libraries/aws_ec2_launch_templates.rb
> +          launch_template_ids: launch_template.launch_template_id,
Alignment Please!

2021-05-10 03:54 UTC, sathish-progress commented on libraries/aws_ec2_launch_templates.rb
> +          launch_template_ids: launch_template.launch_template_id,
Did you test this with filters? I could see your filter table custom column registration not pointing to valid columns in 
 the fields that are present in `launch_template_rows`

2021-05-10 03:57 UTC, sathish-progress commented on test/integration/build/aws.tf
> +    name = "test"
same comment as [above](https://github.com/inspec/inspec-aws/pull/327/files?file-filters%5B%5D=.rb&file-filters%5B%5D=.tf#r629034311)

2021-05-10 03:58 UTC, sathish-progress commented on test/integration/build/aws.tf
> +  key_name = "test"
same comment as [above](https://github.com/inspec/inspec-aws/pull/327/files?file-filters%5B%5D=.rb&file-filters%5B%5D=.tf#r629034311)

2021-05-10 03:58 UTC, sathish-progress commented on test/integration/build/aws.tf
> +      Name = "test"
same comment as [above](https://github.com/inspec/inspec-aws/pull/327/files?file-filters%5B%5D=.rb&file-filters%5B%5D=.tf#r629034311)

2021-05-10 03:59 UTC, sathish-progress commented on test/integration/build/aws.tf
> +  image_id = "ami-0a83ebf1ac32a3fbe"
Why is this hardcoded?

2021-05-10 04:01 UTC, sathish-progress requested changes
Please review requested changes..

2021-05-20 05:05 UTC, sathish-progress commented on libraries/aws_ec2_launch_templates.rb
> +             .register_column(:latest_version_number,         field: :launch_template_tags)
typo I guess

2021-05-24 07:44 UTC, sathish-progress requested changes
@Nirbhay1997 Could you please take a look into these suggestions?

2021-05-24 07:51 UTC, sathish-progress commented
also please add resource doc links to readme

2021-05-24 09:25 UTC, sathish-progress approved these changes
LGTM

2021-05-25 12:41 UTC, sathish-progress commented on README.md
> +- [aws_ec2_lauch_template](docs/resources/aws_ec2_launch_template.md)
actually maintain this alphabetically ..

2021-05-26 16:09 UTC, merged