singular and plural resourse and unit test singular
inspec/inspec-aws pull request #340
Opened 2021-04-30 08:18 UTC by Nirbhay1997

Signed-off-by: nirbhay <nkumar@chef.io>

### Description
Added support for VPC endpoint connection notification resource

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-05-12 14:06 UTC, sathish-progress commented on libraries/aws_vpc_endpoint_connection_notification.rb
> +    end
Could you please add one more example like the below?
```suggestion
    describe aws_vpc_endpoint_connection_notification('vpce-12345678123456789') do
      it { should exist }
    end
```

2021-05-12 14:07 UTC, sathish-progress commented on libraries/aws_vpc_endpoint_connection_notification.rb
> +      raise ArgumentError, "#{@__resource_name__}: 'connection_notification_id' must be in the format 'vpce-nfn-' followed by 8 hexadecimal characters."
```suggestion
      raise ArgumentError, "#{@__resource_name__}: 'connection_notification_id' must be in the format 'vpce-nfn-' followed by 8 or 17 hexadecimal characters."
```

2021-05-12 14:32 UTC, sathish-progress commented on libraries/aws_vpc_endpoint_connection_notification.rb
> +    !@vpcen.empty?
this check would fail if `@vpcen` is `nil` and it is highly possible to be nil when the resource request fails!

2021-05-12 14:34 UTC, sathish-progress commented on libraries/aws_vpc_endpoint_connection_notifications.rb
> +      vpcen_rows+=[{ connection_notification_id: vpcen[:connection_notification_id],
why we don't have `vpc_endpoint_id` ?

2021-05-12 14:36 UTC, sathish-progress commented on libraries/aws_vpc_endpoint_connection_notifications.rb
> +                     connection_events: vpcen[:connection_events],
`connection_events` is a nested [collection](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Types/ConnectionNotification.html#connection_events-instance_method)!, you may need to reconsider how we allow the user to filter using this attribute

2021-05-12 14:38 UTC, sathish-progress commented on test/integration/build/aws.tf
> +resource "aws_vpc_endpoint_service" "foo" {
please use valid local names that represent the purpose actually..

2021-05-12 14:41 UTC, sathish-progress commented on test/unit/resources/vpc_endpoint_notification_test.rb
> +
please remove unnecessary new lines

2021-05-12 14:41 UTC, sathish-progress requested changes
Please review suggestions

2021-05-12 14:42 UTC, sathish-progress commented
Also, I am unable to find integration tests and docs for this !

2021-05-25 07:01 UTC, sathish-progress approved these changes
LGTM

2021-05-25 12:46 UTC, sathish-progress commented
please add docs link to readme file

2021-05-25 19:25 UTC, IanMadd commented on docs/resources/aws_vpc_endpoint_notifications.md
> +    end
Are these code blocks correct?

2021-05-28 06:53 UTC, dkumaras commented on docs/resources/aws_vpc_endpoint_notification.md
> +Use the `aws_vpc_endpoint_connection_notification` InSpec audit resource to test properties of a single specific Aws VPC Endpoint Connection Notification.
inspec - lowercase

AWS - caps
notification - check case

2021-05-28 06:56 UTC, dkumaras commented on docs/resources/aws_vpc_endpoint_notification.md
> +A Aws VPC Endpoint Connection Notification is uniquely identified by the Aws VPC Endpoint Connection Notification ID (e.g vpce-123456abcdef12345)
again check the case of AWS

2021-05-28 06:57 UTC, Nirbhay1997 commented on docs/resources/aws_vpc_endpoint_notifications.md
> +    end
Updating

2021-05-28 06:59 UTC, dkumaras commented on docs/resources/aws_vpc_endpoint_notification.md
> +
check the case of 'Aws'

2021-05-28 07:00 UTC, dkumaras commented on docs/resources/aws_vpc_endpoint_notification.md
> +|connection_notification_id                 | The ID of the Aws VPC Endpoint Connection Notification |
periods at end of each column descriptions

2021-05-28 07:02 UTC, dkumaras commented on docs/resources/aws_vpc_endpoint_notification.md
> +|connection_notification_state              | The state of the Aws VPC Endpoint Connection Notification. one of "Enabled", "Disabled. |
The state of the AWS VPC Endpoint Connection Notification. Possible values are Enabled, "Disabled.

2021-05-28 07:06 UTC, dkumaras commented on docs/resources/aws_vpc_endpoint_notification.md
> +Use `should_not` to test the entity should not exist.
that should not exist

2021-05-28 07:15 UTC, dkumaras commented on docs/resources/aws_vpc_endpoint_notifications.md
> +|Property                                   | Description|
check the period at end of 2nd column description

2021-05-28 07:16 UTC, dkumaras commented on docs/resources/aws_vpc_endpoint_notifications.md
> +|connection_notification_state              | The state of the Aws VPC Endpoint Connection Notification. one of "Enabled", "Disabled. |
we can say, possible values are

2021-05-28 07:17 UTC, dkumaras commented on docs/resources/aws_vpc_endpoint_notifications.md
> +This InSpec audit resource has the following special matchers. For a full list of available matchers, please visit our [Universal Matchers page](https://www.inspec.io/docs/reference/matchers/).
spell error - matches

2021-05-31 06:46 UTC, soumyo13 approved these changes

2021-05-31 06:57 UTC, merged