added support for Redshift Clusters
inspec/inspec-aws pull request #359
Opened 2021-05-20 05:20 UTC by Nirbhay1997

Signed-off-by: nirbhay <nkumar@chef.io>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-05-24 19:41 UTC, IanMadd commented on docs/resources/aws_redshift_cluster.md
> +See also the [AWS documentation on Redshift cluster](https://docs.aws.amazon.com/AmazonRedshift/latest/AuroraUserGuide/Aurora.Overview.html).
This link is bad. Is https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.html the correct link?

2021-05-25 11:09 UTC, soumyo13 requested changes
Update the documentation files in the Readme.

2021-05-25 11:09 UTC, soumyo13 commented on libraries/aws_redshift_cluster.rb
> +    raise ArgumentError, "#{@__resource_name__}: cluster_identifier must start with a letter followed by up to 62 letters/numbers/hyphens." if opts[:cluster_identifier] !~ /^[a-z]{1}[0-9a-z\-]{0,62}$
Write this also in the documentation for both singular and plural resources.

2021-05-25 11:09 UTC, soumyo13 commented on libraries/aws_redshift_clusters.rb
> +             .register_column(:cluster_identifier, field: :cluster_identifier)
Change the names to plural names as this is a plural resource.

2021-05-25 11:09 UTC, soumyo13 commented on libraries/aws_redshift_clusters.rb
> +                           availability_zone:               redshift_cluster.availability_zone }]
ome space missing.

2021-05-25 12:31 UTC, sathish-progress commented on libraries/aws_redshift_cluster.rb
> +      rescue Aws::Redshift::Errors::NotAvailableValueError
please confirm if this inherits from Aws::ServiceErrors and remove this rescue conditions

2021-05-25 12:33 UTC, sathish-progress commented on libraries/aws_redshift_cluster.rb
> +      unless @rds_cluster[:cluster_parameter_groups].to_s.empty?
```suggestion
      if  @rds_cluster[:cluster_parameter_groups] && !@rds_cluster[:cluster_parameter_groups].empty?
```

2021-05-25 12:35 UTC, sathish-progress commented on libraries/aws_redshift_cluster.rb
> +        @rds_cluster[:cluster_parameter_groups] = parameter_groups.map { |x| x.values[0] }
what are we trying to do here?

2021-05-25 12:36 UTC, sathish-progress commented on libraries/aws_redshift_cluster.rb
> +  alias encrypted? has_encrypted?
prefer `has_* ` methods only if you plan to implement matchers with arguments. For boolean you should use `be_*` matchers

2021-05-25 12:37 UTC, sathish-progress commented on libraries/aws_redshift_clusters.rb
> +             .register_column(:vpc_id, field: :vpc_id)
column names could be plural

2021-05-25 12:39 UTC, sathish-progress commented on test/integration/verify/controls/aws_redshift_cluster.rb
> +    its ('vpc_id') { should eq 'vpc-6d9d7505' }
VPC ID could be an attribute

2021-05-25 12:39 UTC, sathish-progress commented on test/integration/verify/controls/aws_redshift_clusters.rb
> +    its ('vpc_id') { should include 'vpc-6d9d7505' }
same here

2021-05-25 12:40 UTC, sathish-progress commented
please also update readme with doc links

2021-05-26 15:43 UTC, sathish-progress commented on docs/resources/aws_rds_cluster.md
> +### Parameters
why these changes here ?

2021-05-26 15:54 UTC, sathish-progress approved these changes
LGTM

2021-05-27 17:43 UTC, soumyo13 approved these changes

2021-05-27 17:44 UTC, merged