Added support to audit  Traffic mirror filter
inspec/inspec-aws pull request #491
Opened 2021-07-09 04:41 UTC by Nirbhay1997

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-07-15 17:18 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_filter.rb
> +    "EC2 Traffic Mirror Filter #{@display_name}"
"EC2 Traffic Mirror Filter: #{@display_name}"

2021-08-04 09:40 UTC, soumyo13 commented
Here unit, integration and documentation files are not there.

2021-08-04 09:42 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_filter.rb
> +    describe aws_ec2_traffic_mirror_filter_rule(traffic_mirror_filter_id: 'test-traffic_mirror_filter') do
Change the "test-traffic_mirror_filter" to "tmf-0293f26e86EXAMPLE".

2021-08-04 09:43 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_filter.rb
> +  desc 'Audits EC2 Traffic Mirror Filter'
Change the description to "Describes one or more Traffic Mirror filters."

2021-08-04 09:44 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_filter.rb
> +      traffic_mirror_filters_arguments = { traffic_mirror_filter_ids: [opts[:traffic_mirror_filter_id]] }
Change we change the line to 
traffic_mirror_filters_arguments = { traffic_mirror_filter_ids: [@display_name] }

2021-08-04 09:46 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_filters.rb
> +        traffic_mirror_filters_rows += [{ traffic_mirror_filter_id: traffic_mirror_filter.traffic_mirror_filter_id,
Please add the other properties.

2021-08-04 09:47 UTC, soumyo13 requested changes
Please make the above changes.

2021-08-06 06:30 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_filters.md
> +|tags                         | A list of hashes with each key-value pair corresponding to an EC2 instance tag, e.g, `[{:key=>"Name", :value=>"Testing Box"}, {:key=>"Environment", :value=>"Dev"}]`|
Can you remove the example. that is not required here.

2021-08-06 06:33 UTC, soumyo13 commented on test/integration/verify/controls/aws_ec2_traffic_mirror_filter.rb
> +aws_traffic_filter_id = attribute(:aws_traffic_filter_id, value: '', description: 'aws traffic filter id.')
Use value instead of attribute.

2021-08-06 06:33 UTC, soumyo13 commented on test/integration/verify/controls/aws_ec2_traffic_mirror_filters.rb
> +aws_traffic_filter_id = attribute(:aws_traffic_filter_id, value: '', description: 'aws traffic filter id.')
Use value instead of attribute.

2021-08-18 07:06 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_filter.md
> +traffic_mirror_filter_id must be be provided.
Change it

2021-08-18 07:07 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_filter.md
> +|tags                         | A list of hashes with each key-value pair corresponding to an Traffic Mirror tag, e.g, `[{:key=>"Name", :value=>"Testing Box"}, {:key=>"Environment", :value=>"Dev"}]`|
Change the description.

2021-08-18 07:08 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_filters.md
> +No required parameters
Remove this line.

2021-08-18 07:08 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_filters.md
> +      its('description') { should include 'test-des' }
```suggestion
      its('description') { should include 'test-desription' }
```

2021-08-18 07:08 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_filters.md
> +##### Test that an EC2 Traffic Mirror has the correct tag
change the value

2021-08-18 07:11 UTC, soumyo13 commented on test/integration/verify/controls/aws_ec2_traffic_mirror_filter.rb
> +aws_traffic_filter_desc = value(:aws_traffic_filter_desc, value: '', description: ' description aws traffic filter .')
```suggestion
aws_traffic_filter_desc = value(:aws_traffic_filter_desc, value: '', description: 'description aws traffic filter .')
```

2021-08-18 07:12 UTC, soumyo13 commented on test/integration/verify/controls/aws_ec2_traffic_mirror_filters.rb
> +aws_traffic_filter_desc = value(:aws_traffic_filter_desc, value: '', description: ' description aws traffic filter .')
```suggestion
aws_traffic_filter_desc = value(:aws_traffic_filter_desc, value: '', description: 'description aws traffic filter .')
```

2021-08-18 07:12 UTC, soumyo13 commented on test/unit/resources/aws_ec2_traffic_mirror_filters_test.rb
> +  def test_rejects_invalid_launch_template_endpoint_id
Change the method name

2021-08-18 07:13 UTC, soumyo13 commented on test/unit/resources/aws_ec2_traffic_mirror_filters_test.rb
> +    @addr = AWSEc2TrafficMirrorFilters.new(client_args: { stub_responses: true }, stub_data: [data])
Change the variable name to something meaningful.

2021-08-18 07:13 UTC, soumyo13 requested changes
LGTM. Please make the changes.

2021-09-03 19:25 UTC, IanMadd approved these changes

2021-09-12 14:47 UTC, soumyo13 approved these changes
LGTM

2021-09-12 14:56 UTC, merged