added singular and plural resource
inspec/inspec-aws pull request #493
Opened 2021-07-22 04:07 UTC by Nirbhay1997

Signed-off-by: nirbhay1997 <nkumar@progress.com>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-08-04 09:50 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_session.rb
> +    describe aws_ec2_traffic_mirror_session(traffic_mirror_session_id: 'test-traffic_mirror_session_id') do
Change the value to "TrafficMirrorSessionId"

2021-08-04 09:51 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_session.rb
> +      traffic_mirror_session_arguments = { traffic_mirror_session_ids: [opts[:traffic_mirror_session_id]] }
traffic_mirror_session_arguments = { traffic_mirror_session_ids: [@display_name] }

2021-08-04 09:51 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_session.rb
> +    "EC2 Traffic Mirror Session : #{@display_name}"
"EC2 Traffic Mirror Session ID: #{@display_name}"

2021-08-04 09:54 UTC, soumyo13 commented on test/unit/resources/aws_ec2_traffic_mirror_session_test.rb
> +    mock_lt[:traffic_mirror_session_id] = 'tms-01a6e9ac9f962f154'
Change the values to dummy values.

2021-08-04 09:54 UTC, soumyo13 commented on test/unit/resources/aws_ec2_traffic_mirror_sessions_test.rb
> +    require 'byebug'
Please remove this.

2021-08-04 09:55 UTC, soumyo13 requested changes
Please add the documentation and the integration tests.

2021-08-06 05:17 UTC, Nirbhay1997 commented on libraries/aws_ec2_traffic_mirror_sessions.rb
> +
thanks a lot

2021-08-06 07:17 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_session.md
> +title: About the aws_ec2_traffic_mirror_sessions Resource
aws_ec2_traffic_mirror_session

2021-08-06 07:17 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_session.md
> +Use the `aws_ec2_traffic_mirror_sessions` InSpec audit resource to test properties an AWS Traffic Mirror Session
aws_ec2_traffic_mirror_session

2021-08-06 07:17 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_session.md
> +An `aws_ec2_launch_template` resource block declares the tests for a single  AWS Traffic Mirror Session by traffic_mirror_session_id.
aws_ec2_traffic_mirror_session

2021-08-06 07:17 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_session.md
> +An `aws_ec2_traffic_mirror_session` resource block declares the tests for an  AWS Traffic Mirror Sessions
AWS Traffic Mirror Session

2021-08-06 07:18 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_session.md
> +##### Test that an should exist
Change the description

2021-08-06 07:18 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_session.md
> +    describe aws_ec2_traffic_mirror_session(traffic_mirror_session_id: 'test-traffic_mirror_session_id') do
Change the description

2021-08-06 07:18 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_session.md
> +##### Test that an EC2 instance has the correct tag
Change the description

2021-08-06 07:19 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_sessions.md
> +##### Test that Traffic  mirror target includes a value
Change the description

2021-08-06 07:19 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_sessions.md
> +## Matchers
Add matchers.

2021-08-06 07:20 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_session.rb
> +    "EC2 Traffic Mirror Session : #{@display_name}"
"EC2 Traffic Mirror Session ID: #{@display_name}"

2021-08-06 07:20 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_sessions.rb
> +
Remove the line.

2021-08-06 07:23 UTC, soumyo13 requested changes
Please review comments.

2021-08-06 07:23 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_sessions.rb
> +
remove the line.

2021-08-06 07:23 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_sessions.rb
> +
remove the extra line.

2021-08-06 07:23 UTC, soumyo13 commented on libraries/aws_ec2_traffic_mirror_sessions.rb
> +    @pagination_options = {}
pagination_options - we can use this.

2021-08-06 07:23 UTC, soumyo13 commented on test/unit/resources/aws_ec2_traffic_mirror_session_test.rb
> +    @addr = AWSEc2TrafficMirrorSession.new(traffic_mirror_session_id: 'tms-01a6e9ac9f962f154',client_args: { stub_responses: true }, stub_data: [data])
Change the var name.

2021-08-06 07:23 UTC, soumyo13 commented on test/unit/resources/aws_ec2_traffic_mirror_session_test.rb
> +    mock_lt[:traffic_mirror_target_id] = 'tmt-01a6e9ac9f962f154'
tmt-01a6e9ac9f962f154 should be tmt-1234567890

2021-08-06 07:23 UTC, soumyo13 commented on test/unit/resources/aws_ec2_traffic_mirror_sessions_test.rb
> +    @addr = AWSEc2TrafficMirrorSessions.new(client_args: { stub_responses: true }, stub_data: [data])
Same here

2021-08-06 07:23 UTC, soumyo13 commented on test/unit/resources/aws_ec2_traffic_mirror_sessions_test.rb
> +    mock_lt[:traffic_mirror_session_id] = 'tms-01a6e9ac9f962f154'
Change the hardcoded values.

2021-08-18 06:59 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_session.md
> +
End the line

2021-08-18 07:00 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_session.md
> +##### traffic\_mirror_\session_\id
Remove line no. 24. and make it as required.

2021-08-18 07:01 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_sessions.md
> +Use the `aws_ec2_traffic_mirror_sessions` InSpec audit resource to test properties of a all the AWS Traffic Mirror Sessions
```suggestion
Use the `aws_ec2_traffic_mirror_sessions` InSpec audit resource to test properties of a all the AWS Traffic Mirror Sessions.
```

2021-08-18 07:01 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_sessions.md
> +An `aws_ec2_traffic_mirror_sessions` resource block declares the tests for a all the  AWS Traffic Mirror Sessions
```suggestion
An `aws_ec2_traffic_mirror_sessions` resource block declares the tests for all the  AWS Traffic Mirror Sessions.
```

2021-08-18 07:01 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_sessions.md
> +
```suggestion
```

2021-08-18 07:02 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_sessions.md
> +  its('description') { should include 'test-lt' }
```suggestion
  its('description') { should include 'test-description' }
```

2021-08-18 07:03 UTC, soumyo13 commented on test/unit/resources/aws_ec2_traffic_mirror_session_test.rb
> +  def test_rejects_invalid_launch_template_endpoint_id
Change the method name

2021-08-18 07:04 UTC, soumyo13 requested changes
Please make the changes

2021-09-01 06:57 UTC, soumyo13 commented on docs/resources/aws_ec2_traffic_mirror_session.md
> +      its('traffic_mirror_session_id') { should eq 'test-lt' }
its('traffic_mirror_session_id') { should eq 'test-traffic_mirror_session_id' }

2021-09-08 06:47 UTC, soumyo13 approved these changes
LGTM

2021-09-08 21:38 UTC, IanMadd approved these changes

2021-09-12 15:26 UTC, merged