Added support to audit the status of a service-linked role deletion.
inspec/inspec-aws pull request #514
Opened 2021-08-16 13:31 UTC by Nirbhay1997

Signed-off-by: nirbhay1997 <nkumar@progress.com>

### Description

Added support to audit the status of a service-linked role deletion.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-08-18 06:27 UTC, soumyo13 commented on libraries/aws_iam_service_linked_role_deletion_status.rb
> +    "deletion_task_id: #{@display_name}"
```suggestion
    "Deletion Task ID: #{@display_name}"
```

2021-08-18 06:27 UTC, soumyo13 commented on test/unit/resources/aws_iam_service_linked_role_deletion_status_test.rb
> +  def test_parameter_group_exists
Change the method name.

2021-08-18 06:29 UTC, soumyo13 commented on docs/resources/aws_iam_service_linked_role_deletion_status.md
> +
Add what is deletion_task_id!

2021-08-18 06:30 UTC, soumyo13 commented on docs/resources/aws_iam_service_linked_role_deletion_status.md
> +    describe aws_iam_service_linked_role_deletion_status(deletion_task_id: 'deletion_task_id') do
Change all the deletion_task_id to some meaningful values.

2021-08-18 06:32 UTC, soumyo13 requested changes
LGTM. Please add the tests.

2021-08-18 06:33 UTC, soumyo13 commented
Please change the description of the PR.

2021-08-22 12:33 UTC, soumyo13 approved these changes
LGTM

2021-09-13 20:00 UTC, IanMadd approved these changes

2021-09-16 09:30 UTC, merged