Nirbhay/ Network Manager Device
inspec/inspec-aws pull request #537
Opened 2021-09-01 07:41 UTC by Nirbhay1997

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-09-01 09:06 UTC, soumyo13 requested changes
Add Terraform and Buildkite is failing.

2021-09-16 11:21 UTC, soumyo13 approved these changes
LGTM

2021-10-04 21:28 UTC, IanMadd commented on docs/resources/aws_network_manager_devices.md
> +      its('aws_location.zone') { should include 'ZONE_NAME' }
Should this be `aws_locations.zone`?

2021-10-05 10:39 UTC, Nirbhay1997 commented on docs/resources/aws_network_manager_devices.md
> +      its('aws_location.zone') { should include 'ZONE_NAME' }
thanks updated

2021-10-06 00:13 UTC, IanMadd approved these changes

2021-11-23 16:04 UTC, IanMadd approved these changes

2021-11-25 06:57 UTC, merged