added resources and test cases
inspec/inspec-aws pull request #539
Opened 2021-09-01 08:15 UTC by Nirbhay1997

Signed-off-by: Nirbhay Kumar <nkumar@progress.com>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-09-01 09:03 UTC, soumyo13 commented on docs/resources/aws_network_manager_global_networks.md
> +Use the `aws_network_manager_global_networks` InSpec audit resource to test properties of a single specific AWS Network Manager Global Network.
Change this description.

2021-09-01 09:04 UTC, soumyo13 requested changes
Add Terraform.

2021-09-06 01:20 UTC, Nirbhay1997 commented
No Terraform is available for the resource : https://github.com/hashicorp/terraform-provider-aws/issues/11132

2021-09-06 02:08 UTC, Nirbhay1997 commented
(byebug) @aws.network_manager_client.describe_global_networks(pagination_options)

*** Seahorse::Client::NetworkingError Exception: Failed to open TCP connection to networkmanager.xxxx-2.amazonaws.com:xxx (getaddrinfo: Name or service not known)
**_### Probably a bug in ruby sdk_**

2021-09-16 09:24 UTC, soumyo13 approved these changes
LGTM

2021-10-04 23:33 UTC, IanMadd approved these changes

2021-10-05 09:10 UTC, merged