Feature request for CloudFormation Template
inspec/inspec-aws pull request #770
Opened 2021-11-19 16:41 UTC by jb897

Signed-off-by: Josh Bowman <joshua.bowman@sap.com>

### Description

This change allows the template_body property to be accessed from the aws_cloudformation_template resource.
Another AWS SDK API call to get_template is added, along with a function to retrieve the data stored. One caveat, is that the stack_name parameter must be used in the resource, since this is the only parameter that the API call will accept related to the cloudformation_templates

### Issues Resolved
Needed to access information from the template body when accessing a cloudformation_template.

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [x] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [x] `rake lint` passes
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-11-21 14:52 UTC, soumyo13 requested changes
Please check the comment.

2021-11-21 14:52 UTC, soumyo13 commented on docs/resources/aws_cloudformation_template.md
> +(to access this property, the `stack_name` must be passed in as a parameter).   |
```suggestion
| template_body                                 | The structure that contains the body of the template (to access this property, the `stack_name` must be passed in as a parameter).   |
```

2021-11-23 17:16 UTC, jb897 commented
My fault, hadn't updated the branch. Sorry about that.

2021-11-23 19:12 UTC, IanMadd commented on docs/resources/aws_cloudformation_template.md
> +| template_body                                 | The structure that contains the body of the template (to access this property, the `stack_name` must be passed in as a parameter).   |
```suggestion
| template_body                                 | The structure that contains the body of the template. The `stack_name` must be passed as a parameter to access this property. |
```

2021-11-24 06:19 UTC, soumyo13 commented on docs/resources/aws_cloudformation_template.md
> +| template_body                                 | The structure that contains the body of the template (to access this property, the `stack_name` must be passed in as a parameter).   |
@jb897 Please check @IanMadd suggestion.

2021-11-26 07:51 UTC, Nirbhay1997 reviewed
Hi , @jb897   could you please update the tests with this attribute?

2021-11-30 16:37 UTC, jb897 commented
> Sorry for the delay. Was out of office due to Thanksgiving.

2021-12-02 04:53 UTC, Nirbhay1997 commented
@jb897  could you please add unit tests and integration tests for the attribute?

2021-12-06 19:33 UTC, sathish-progress commented
> @jb897 could you please add unit tests and integration tests for the attribute?

As requested by @jonlives in the slack channel, to unblock current implementation of the controls by the customer, approving this one!  Tests for this either way is a minor one and can be part of a separate PR ..

Hey @jb897, please raise a separate PR for the tests once you are done with the implementation of them..

2021-12-06 19:33 UTC, sathish-progress approved these changes
LGTM

2021-12-06 19:34 UTC, merged

2021-12-07 06:23 UTC, Nirbhay1997 commented
Hi  @jb897,  The attribute `template_body`  is not working for me instead  I need to use it like this  
`template_body.template_body`. Could you please parse it properly so that we can use  template_body  ??

2021-12-10 09:06 UTC, jb897 commented
> Hi @jb897, The attribute `template_body` is not working for me instead I need to use it like this `template_body.template_body`. Could you please parse it properly so that we can use template_body ??

Hi @Nirbhay1997, I hadn't realized I've been adding this locally, do you still want me to make a PR to include this in the resource pack? Apologies for the late response.