Added Support to Audit RDS Global Clusters
inspec/inspec-aws pull request #780
Opened 2021-11-24 02:19 UTC by Nirbhay1997

Signed-off-by: Nirbhay Kumar <nkumar@progress.com>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-11-24 06:27 UTC, soumyo13 requested changes

2021-11-24 06:27 UTC, soumyo13 commented on libraries/aws_rds_global_cluster.rb
> +    describe aws_rds_global_cluster(global_cluster_identifier: 'DB_PROXY_NAME') do
```suggestion
    describe aws_rds_global_cluster(global_cluster_identifier: 'GLOBAL_CLUSTER_IDENTIFIER') do
```

2021-11-24 06:27 UTC, soumyo13 commented on libraries/aws_rds_global_cluster.rb
> +    "RDS Global cluster identifier: #{@display_name}"
```suggestion
    "RDS Global Cluster Identifier: #{@display_name}"
```

2021-11-24 06:27 UTC, soumyo13 commented on libraries/aws_rds_global_cluster.rb
> +  desc 'Returns information about DB proxies.'
```suggestion
  desc 'Returns information about Aurora global database clusters.'
```

2021-11-25 08:57 UTC, soumyo13 commented on test/unit/resources/aws_rds_global_cluster_test.rb
> +  def test_statuses
```suggestion
  def test_status
```

2021-11-25 09:02 UTC, Nirbhay1997 commented on docs/resources/aws_rds_global_clusters.md
> +Your [Principal](https://docs.aws.amazon.com/IAM/latest/UserGuide/intro-structure.html#intro-structure-principal) will need the `RDS:Client:DescribeDBProxyTargetGroupsResponse` action with `Effect` s
```suggestion
Your [Principal](https://docs.aws.amazon.com/IAM/latest/UserGuide/intro-structure.html#intro-structure-principal) will need the `RDS:Client:DescribeGlobalClustersMessage` action with `Effect` set to `Allow`.
```

2021-11-25 09:02 UTC, soumyo13 commented on docs/resources/aws_rds_global_cluster.md
> +### Ensure a db global cluster ID name is available.
```suggestion
### Ensure a DB global cluster is available.
```

2021-11-25 09:02 UTC, soumyo13 commented on docs/resources/aws_rds_global_clusters.md
> +The AWS::RDS::DBProxyTargetGroup resource represents a set of RDS DB instances, Aurora DB clusters, or both that a proxy can connect to.
```suggestion
```

2021-11-25 09:03 UTC, soumyo13 commented on docs/resources/aws_rds_global_clusters.md
> +Ensure that the target group exists.
```suggestion
Ensure that the global cluster exists.
```

2021-11-25 09:04 UTC, soumyo13 commented on docs/resources/aws_rds_global_clusters.md
> +      its('global_cluster_identifiers') { should include 'DB_PROXY_NAME' }
```suggestion
      its('global_cluster_identifiers') { should include 'GLOBAL_CLUSTER_IDENTIFIER' }
```

2021-11-25 09:04 UTC, soumyo13 commented on docs/resources/aws_rds_global_clusters.md
> +      its('global_cluster_resource_ids') { should include 'TARGET_GROUP_NAME' }
```suggestion
      its('global_cluster_resource_ids') { should include 'GLOBAL_CLUSTER_RESOURCE_ID' }
```

2021-11-25 09:05 UTC, soumyo13 commented on docs/resources/aws_rds_global_clusters.md
> +
```suggestion
```

2021-11-25 09:07 UTC, soumyo13 commented on docs/resources/aws_rds_global_cluster.md
> +The AWS::RDS::DBProxyTargetGroup resource represents a set of RDS DB instances, Aurora DB clusters, or both that a proxy can connect to.
```suggestion
```

2021-11-25 09:08 UTC, soumyo13 commented on docs/resources/aws_rds_global_cluster.md
> +
```suggestion
```

2021-11-25 09:08 UTC, soumyo13 commented on docs/resources/aws_rds_global_cluster.md
> +    describe aws_rds_global_cluster(global_cluster_identifier: 'GLOBAL_CLUSTER_IDENTIFIER'') do
```suggestion
    describe aws_rds_global_cluster(global_cluster_identifier: 'GLOBAL_CLUSTER_IDENTIFIER') do
```

2021-11-25 09:09 UTC, soumyo13 approved these changes

2021-11-30 17:53 UTC, IanMadd approved these changes

2021-12-05 06:08 UTC, merged