Added Support for RDS Event Subscription
inspec/inspec-aws pull request #781
Opened 2021-11-24 03:07 UTC by Nirbhay1997

Signed-off-by: Nirbhay Kumar <nkumar@progress.com>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-11-24 06:24 UTC, soumyo13 requested changes

2021-11-24 06:24 UTC, soumyo13 commented on libraries/aws_rds_event_subscription.rb
> +    "RDS Event Subscription name: #{@display_name}"
```suggestion
    "RDS Event Subscription Name: #{@display_name}"
```

2021-11-25 06:06 UTC, soumyo13 requested changes

2021-11-25 06:06 UTC, soumyo13 commented on docs/resources/aws_rds_event_subscriptions.md
> +    end
```suggestion
### Ensure an event subscription name is available.
    describe aws_rds_event_subscriptions do
      its('cust_subscription_ids') { should eq 'CUST_SUBSCRIPTION_ID' }
    end

### Ensure an event subscription SNS Topic ARN is available.
    describe aws_rds_event_subscriptions do
      its('sns_topic_arns') { should eq 'SNS_TOPIC_ARN' }
    end

### Ensure a customer AWS ID is available.
    describe aws_rds_event_subscriptions do
      its('customer_aws_ids') { should eq 'CUSTOMER_AWS_ID' }
    end
```

2021-11-25 06:06 UTC, soumyo13 commented on libraries/aws_rds_event_subscription.rb
> +    describe aws_rds_event_subscription(subscription_name: 'SUBSCRIPTION_NAME') do
```suggestion
    describe aws_rds_event_subscription(subscription_name: 'EVENT_SUBSCRIPTION_NAME') do
```

2021-11-25 06:06 UTC, soumyo13 commented on test/integration/build/aws.tf
> +resource "aws_subnet" "for_proxy" {
```suggestion
#AWS::RDS::EventSubscription
resource "aws_vpc" "for_proxy" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "for_proxy" {
```

2021-11-25 06:06 UTC, soumyo13 commented on test/integration/build/aws.tf
> +  tags = {
```suggestion

  tags = {
```

2021-11-25 06:06 UTC, soumyo13 commented on test/integration/build/aws.tf
> +  tags = {
```suggestion

  tags = {
```

2021-11-25 06:06 UTC, soumyo13 commented on test/integration/build/aws.tf
> +resource "aws_db_parameter_group" "default" {
```suggestion
}

resource "aws_db_parameter_group" "default" {
```

2021-11-25 06:06 UTC, soumyo13 commented on test/integration/verify/controls/aws_rds_event_subscriptions.rb
> +event_subscription = attribute(:event_subscription, value: '', description: 'The AWS Auto Scaling Group name.')
```suggestion
event_subscription = attribute(:event_subscription, value: '', description: '')
```

2021-11-25 06:06 UTC, soumyo13 commented on test/integration/verify/controls/aws_rds_event_subscription.rb
> +event_subscription = attribute(:event_subscription, value: '', description: 'The AWS Auto Scaling Group name.')
```suggestion
event_subscription = attribute(:event_subscription, value: '', description: '')
```

2021-11-25 06:06 UTC, soumyo13 commented on test/integration/verify/controls/aws_rds_event_subscriptions.rb
> +  title 'Test the properties of Event Subscription.'
```suggestion
  title 'Test the properties of Event Subscriptions.'
```

2021-11-25 07:07 UTC, soumyo13 approved these changes

2021-11-30 19:15 UTC, IanMadd approved these changes

2021-12-05 05:48 UTC, merged