Added Support for db security group
inspec/inspec-aws pull request #782
Opened 2021-11-24 04:10 UTC by Nirbhay1997

Signed-off-by: Nirbhay Kumar <nkumar@progress.com>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-11-24 06:22 UTC, soumyo13 requested changes

2021-11-24 06:22 UTC, soumyo13 commented on libraries/aws_rds_db_security_group.rb
> +    describe aws_rds_db_security_group(db_security_group_name: 'SECURITY_GROUP_NAME') do
```suggestion
    describe aws_rds_db_security_group(db_security_group_name: 'DB_SECURITY_GROUP_NAME') do
```

2021-11-24 06:22 UTC, soumyo13 commented on libraries/aws_rds_db_security_group.rb
> +  def ec2_security_group_name
```suggestion
  def ec2_security_group_names
```

2021-11-24 06:22 UTC, soumyo13 commented on libraries/aws_rds_db_security_group.rb
> +  def ec2_security_group_id
```suggestion
  def ec2_security_group_ids
```

2021-11-24 06:22 UTC, soumyo13 commented on libraries/aws_rds_db_security_group.rb
> +  def ec2_security_group_owner_id
```suggestion
  def ec2_security_group_owner_ids
```

2021-11-24 06:22 UTC, soumyo13 commented on libraries/aws_rds_db_security_group.rb
> +  def status
```suggestion
  def statuses
```

2021-11-24 06:22 UTC, soumyo13 commented on libraries/aws_rds_db_security_group.rb
> +  def cidrip
```suggestion
  def cidrips
```

2021-11-25 07:32 UTC, soumyo13 approved these changes

2021-11-30 19:23 UTC, IanMadd approved these changes

2021-12-05 05:18 UTC, merged