added resourcce and test
inspec/inspec-aws pull request #783
Opened 2021-11-24 19:08 UTC by Nirbhay1997

Signed-off-by: Nirbhay Kumar <nkumar@progress.com>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-11-25 07:36 UTC, soumyo13 commented on libraries/aws_s3_bucket_policy.rb
> +    describe aws_s3_bucket_policy(bucket: 'DB_PROXY_NAME') do
```suggestion
    describe aws_s3_bucket_policy(bucket: 'BUCKET_NAME') do
```

2021-11-25 07:36 UTC, soumyo13 commented on libraries/aws_s3_bucket_policy.rb
> +    "S3 Bucket name: #{@display_name}"
```suggestion
    "S3 Bucket Name: #{@display_name}"
```

2021-11-25 07:37 UTC, soumyo13 commented on test/unit/resources/aws_s3_bucket_policy_test.rb
> +    assert_raises(ArgumentError) { AWSRDSS3Policy.new(bucket: '', db_proxy_endpoint_name: '', client_args: { stub_responses: true }) }
```suggestion
    assert_raises(ArgumentError) { AWSRDSS3Policy.new(bucket: '', client_args: { stub_responses: true }) }
```

2021-11-25 07:38 UTC, soumyo13 commented on libraries/aws_s3_bucket_policy.rb
> +  desc 'Retrieves information about a bucket policy'
```suggestion
  desc 'Retrieves information about a bucket policy.'
```

2021-12-05 06:00 UTC, soumyo13 requested changes

2021-12-05 06:00 UTC, soumyo13 commented on test/integration/verify/controls/aws_s3_bucket_policy.rb
> +end
```suggestion
bucket_name = attribute(:bucket_name, value: '')

control 'aws-s3-bucket-policy-1.0' do

  impact 1.0
  title 'Test the properties of an S3 Bucket Policy.'
  
  describe aws_s3_bucket_policy(bucket: bucket_name) do
    it { should exist }
    its('policy') { should_not empty }
  end
end
```

2021-12-05 07:17 UTC, soumyo13 commented
Here I have added the BucketPolicy in the Readme.md file. No need of creating a separate PR for this. @Nirbhay1997

2021-12-14 05:59 UTC, soumyo13 approved these changes

2021-12-14 19:22 UTC, IanMadd approved these changes

2021-12-15 05:37 UTC, merged