AWS_WAF_RULE
inspec/inspec-aws pull request #802
Opened 2021-12-11 20:37 UTC by Nirbhay1997

Signed-off-by: Nirbhay Kumar <nkumar@progress.com>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-12-13 03:48 UTC, soumyo13 requested changes

2021-12-13 03:48 UTC, soumyo13 commented on libraries/aws_waf_rule.rb
> +    describe aws_waf_rule(rule_id: 'BucketName') do
```suggestion
    describe aws_waf_rule(rule_id: 'RULE_ID') do
```

2021-12-13 03:48 UTC, soumyo13 commented on test/unit/resources/aws_waf_rule_test.rb
> +  def test_rule_id
```suggestion
  def test_name
```

2021-12-13 03:48 UTC, soumyo13 commented on test/unit/resources/aws_waf_rule_test.rb
> +  def rule_id
```suggestion
  def test_rule_id
```

2021-12-13 03:48 UTC, soumyo13 commented on test/unit/resources/aws_waf_rules_test.rb
> +end
```suggestion

  def test_names
    assert_equal(@resp.names, ['name'])
  end
end
```

2021-12-14 10:01 UTC, soumyo13 approved these changes

2021-12-14 20:14 UTC, IanMadd approved these changes

2021-12-15 06:02 UTC, merged