AWS_WAF_ByteMatchSet
inspec/inspec-aws pull request #803
Opened 2021-12-11 21:49 UTC by Nirbhay1997

Signed-off-by: Nirbhay Kumar <nkumar@progress.com>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-12-13 03:52 UTC, soumyo13 requested changes

2021-12-13 03:52 UTC, soumyo13 commented on libraries/aws_waf_byte_match_set.rb
> +    describe aws_waf_byte_match_set(byte_match_set_id: 'BucketName') do
```suggestion
    describe aws_waf_byte_match_set(byte_match_set_id: 'BYTE_MATCH_SET_ID') do
```

2021-12-13 03:52 UTC, soumyo13 commented on libraries/aws_waf_byte_match_set.rb
> +    "Resource ID: #{@display_name}"
```suggestion
    "Byte Match Set ID: #{@display_name}"
```

2021-12-13 03:52 UTC, soumyo13 commented on test/unit/resources/aws_waf_byte_match_set_test.rb
> +  def test_rule_exists
```suggestion
  def test_byte_match_set_exists
```

2021-12-13 03:52 UTC, soumyo13 commented on test/unit/resources/aws_waf_byte_match_sets_test.rb
> +    assert_raises(ArgumentError) { AWSWAFByteMatchSets.new(test: 'rubbish') }
```suggestion
    assert_raises(ArgumentError) { AWSWAFByteMatchSets.new(test: 'dummy') }
```

2021-12-13 03:52 UTC, soumyo13 commented on test/unit/resources/aws_waf_byte_match_sets_test.rb
> +  def test_rule_exists
```suggestion
  def test_byte_match_set_exists
```

2021-12-14 10:06 UTC, soumyo13 commented on test/unit/resources/aws_waf_byte_match_sets_test.rb
> +  def test_rule_ids
```suggestion
  def test_byte_match_set_ids
```

2021-12-14 10:08 UTC, soumyo13 approved these changes

2021-12-16 00:10 UTC, IanMadd approved these changes

2021-12-16 00:10 UTC, IanMadd approved these changes

2021-12-27 05:42 UTC, merged