Aws WAF IP Set
inspec/inspec-aws pull request #804
Opened 2021-12-12 11:24 UTC by Nirbhay1997

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-12-13 03:55 UTC, soumyo13 requested changes

2021-12-13 03:55 UTC, soumyo13 commented on libraries/aws_waf_ip_set.rb
> +    describe aws_waf_ip_set(ip_set_id: 'IP_SET_NAME') do
```suggestion
    describe aws_waf_ip_set(ip_set_id: 'IP_SET_ID') do
```

2021-12-13 03:55 UTC, soumyo13 commented on libraries/aws_waf_ip_set.rb
> +    "Resource ID: #{@display_name}"
```suggestion
    "IP Set ID: #{@display_name}"
```

2021-12-13 03:55 UTC, soumyo13 commented on test/unit/resources/aws_waf_ip_set_test.rb
> +  def test_byte_match_set_name
Change it!

2021-12-13 04:30 UTC, soumyo13 commented on libraries/aws_waf_ip_set.rb
> +    "Resource ID: #{@display_name}"
```suggestion
    "IP Set ID: #{@display_name}"
```

2021-12-14 10:11 UTC, soumyo13 commented on docs/resources/aws_waf_ip_set.md
> +      its('ip_set_id') { should eq 'WEB_ACL_ID' }
```suggestion
      its('ip_set_id') { should eq 'IP_SET_ID' }
```

2021-12-14 10:11 UTC, soumyo13 commented on docs/resources/aws_waf_ip_set.md
> +        its('name') { should eq 'WEB_ACL_NAME' }
```suggestion
        its('name') { should eq 'IP_SET_NAME' }
```

2021-12-14 10:11 UTC, soumyo13 commented on docs/resources/aws_waf_ip_sets.md
> +      its('ip_set_id') { should include 'WEB_ACL_ID' }
```suggestion
      its('ip_set_ids') { should include 'IP_SET_ID' }
```

2021-12-14 10:11 UTC, soumyo13 commented on docs/resources/aws_waf_ip_sets.md
> +        its('name') { should include 'WEB_ACL_NAME' }
```suggestion
        its('names') { should include 'IP_SET_NAME' }
```

2021-12-14 10:16 UTC, Nirbhay1997 commented on test/unit/resources/aws_waf_ip_set_test.rb
> +  def test_byte_match_set_name
```suggestion
  def test_ip_set_name
```

2021-12-14 10:17 UTC, Nirbhay1997 commented on test/unit/resources/aws_waf_ip_set_test.rb
> +  def test_rule_exists
```suggestion
  def test_ip_set_exists
```

2021-12-14 10:18 UTC, Nirbhay1997 commented on test/unit/resources/aws_waf_ip_sets_test.rb
> +  def test_rule_exists
```suggestion
  def test_ip_set_exists
```

2021-12-14 10:18 UTC, Nirbhay1997 commented on test/unit/resources/aws_waf_ip_sets_test.rb
> +  def test_rule_ids
```suggestion
  def test_ip_set_ids
```

2021-12-14 10:20 UTC, Nirbhay1997 commented on test/unit/resources/aws_waf_ip_set_test.rb
> +  def test_rule_exists
```suggestion
  def test_ip_set_exists
```

2021-12-14 10:21 UTC, Nirbhay1997 commented on test/unit/resources/aws_waf_ip_set_test.rb
> +  def test_rule_exists
```suggestion
  def test_ip_set_exists
```

2021-12-14 10:29 UTC, soumyo13 approved these changes

2021-12-17 22:55 UTC, IanMadd approved these changes

2021-12-27 06:45 UTC, merged