resource and unit tests
inspec/inspec-aws pull request #805
Opened 2021-12-12 12:33 UTC by Nirbhay1997

Signed-off-by: Nirbhay Kumar <nkumar@progress.com>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-12-13 03:58 UTC, soumyo13 requested changes

2021-12-13 03:58 UTC, soumyo13 commented on libraries/aws_waf_size_constraint_set.rb
> +    describe aws_waf_size_constraint_set(size_constraint_set_id: 'BucketName') do
```suggestion
    describe aws_waf_size_constraint_set(size_constraint_set_id: 'SET_CONSTRAINT_SET_ID') do
```

2021-12-13 03:58 UTC, soumyo13 commented on libraries/aws_waf_size_constraint_set.rb
> +    "Resource ID: #{@display_name}"
```suggestion
    "Size Constraint Set ID: #{@display_name}"
```

2021-12-13 03:58 UTC, soumyo13 commented on test/unit/resources/aws_waf_size_constraint_set_test.rb
> +  def test_rule_exists
```suggestion
  def test_size_constraint_set_exists
```

2021-12-13 03:58 UTC, soumyo13 commented on test/unit/resources/aws_waf_size_constraint_set_test.rb
> +  def test_byte_match_set_name
```suggestion
  def test_name
```

2021-12-13 03:58 UTC, soumyo13 commented on test/unit/resources/aws_waf_size_constraint_sets_test.rb
> +  def test_rule_ids
```suggestion
  def test_size_constraint_set_ids
```

2021-12-13 03:58 UTC, soumyo13 commented on test/unit/resources/aws_waf_size_constraint_sets_test.rb
> +  def test_rule_exists
```suggestion
  def test_size_constraint_set_exists
```

2021-12-14 10:25 UTC, soumyo13 approved these changes

2021-12-17 23:18 UTC, IanMadd approved these changes

2021-12-27 06:29 UTC, merged