added resource and unit test cases
inspec/inspec-aws pull request #808
Opened 2021-12-12 19:58 UTC by Nirbhay1997

Signed-off-by: Nirbhay Kumar <nkumar@progress.com>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec AWS](https://github.com/inspec/inspec-aws/CONTRIBUTING.md) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-12-13 04:09 UTC, soumyo13 requested changes

2021-12-13 04:09 UTC, soumyo13 commented on libraries/aws_waf_web_acl.rb
> +    describe aws_waf_web_acl(web_acl_id: 'ResourceId') do
```suggestion
    describe aws_waf_web_acl(web_acl_id: 'WEB_ACL_ID') do
```

2021-12-13 04:09 UTC, soumyo13 commented on libraries/aws_waf_web_acl.rb
> +    "Resource ID: #{@display_name}"
```suggestion
    "Web ACL ID: #{@display_name}"
```

2021-12-13 04:09 UTC, soumyo13 commented on test/integration/verify/controls/aws_waf_web_acl.rb
> +  describe aws_waf_web_acl(web_acl_id: aws_waf_web_acl_id) do
```suggestion
  title 'Test the properties of single WAF ACL.'
  
  describe aws_waf_web_acl(web_acl_id: aws_waf_web_acl_id) do
```

2021-12-13 04:09 UTC, soumyo13 commented on test/integration/verify/controls/aws_waf_web_acls.rb
> +  describe aws_waf_web_acls do
```suggestion
  title 'Test the properties of all the WAF ACLs.'
  
  describe aws_waf_web_acls do
```

2021-12-13 04:09 UTC, soumyo13 commented on test/unit/resources/aws_waf_web_acl_test.rb
> +  def test_web_acl_name
```suggestion
  def test_name
```

2021-12-14 10:14 UTC, soumyo13 approved these changes

2021-12-30 17:18 UTC, IanMadd approved these changes

2022-01-03 05:40 UTC, merged