Add attributes to ebs volumes resource
inspec/inspec-aws pull request #813
Opened 2021-12-14 16:38 UTC by jnikles1

Signed-off-by: Justin Nikles <justin.nikles@sap.com>

### Description

Added attributes to the ebs volumes resource so that additional attributes other than the volume_id can be accessed

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources
- [ ] All Integration Tests pass 
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-12-15 05:55 UTC, soumyo13 commented on libraries/aws_ebs_volumes.rb
>        return [] if !@api_response || @api_response.empty?
```suggestion
      return volume_rows if !@api_response || @api_response.empty?
```

2021-12-15 05:57 UTC, soumyo13 requested changes
Please update the documentation, integration tests, and also unit tests. Please add the parameter max_results in the plural resource.

2021-12-16 15:49 UTC, jnikles1 commented
@soumyo13 where would you like me to add the max_results parameter? Looking at this resource as an example but I don't see any max results parameter https://github.com/inspec/inspec-aws/blob/main/libraries/aws_efs_file_systems.rb

2021-12-16 21:56 UTC, jnikles1 commented
@soumyo13 do you have any documentation on creating these integration and unit tests?

2021-12-17 03:40 UTC, soumyo13 commented
> @soumyo13 where would you like me to add the max_results parameter? Looking at this resource as an example but I don't see any max results parameter https://github.com/inspec/inspec-aws/blob/main/libraries/aws_efs_file_systems.rb

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Client.html#describe_volumes-instance_method
Please see the above link. And also see the response.

Resp:
resp = client.describe_volumes({
  filters: [
    {
      name: "String",
      values: ["String"],
    },
  ],
  volume_ids: ["VolumeId"],
  dry_run: false,
  **max_results: 1,**
  next_token: "String",
})

2021-12-17 03:45 UTC, soumyo13 commented
> @soumyo13 do you have any documentation on creating these integration and unit tests?

Please check the below links for the following:
For documentation: https://github.com/inspec/inspec-aws/blob/main/docs/resources/aws_ebs_volumes.md
As you have added other parameters, you have to update the docs with the parameters that you have added. As of now there is only one parameter that is added.

For unit tests: You have to write the unit test as you have added the parameters you have added in the plural resource.

For integration tests: Please add the integration tests which will test the parameters that you have added in the plural resource.

2021-12-21 14:41 UTC, jnikles1 commented
> > @soumyo13 where would you like me to add the max_results parameter? Looking at this resource as an example but I don't see any max results parameter https://github.com/inspec/inspec-aws/blob/main/libraries/aws_efs_file_systems.rb
> 
> https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Client.html#describe_volumes-instance_method Please see the above link. And also see the response.
> 
> Resp: resp = client.describe_volumes({ filters: [ { name: "String", values: ["String"], }, ], volume_ids: ["VolumeId"], dry_run: false, **max_results: 1,** next_token: "String", })

Hi @soumyo13 - still not understanding as I don't see this parameter in other resources. Can you point me to an example so that I can see an example implementation?

2021-12-21 14:48 UTC, soumyo13 commented
Can we have a call tomorrow?

2021-12-21 14:50 UTC, jnikles1 commented
Yes that would be great

2021-12-27 07:01 UTC, soumyo13 commented
@jnikles1 Any update on this?

2021-12-28 14:37 UTC, jnikles1 commented
@soumyo13 - apologies, was away for the holidays. The work is almost done and should be pushed today

2021-12-29 08:31 UTC, Nirbhay1997 commented on test/unit/resources/aws_ebs_volumes_test.rb
> +    volume_id = "ebs-12345"
Do we need this line  ??

2021-12-29 08:32 UTC, Nirbhay1997 commented on test/unit/resources/aws_ebs_volumes_test.rb
> +    volume_id = "ebs-12345"
```suggestion
  
```

2021-12-29 08:33 UTC, Nirbhay1997 commented on test/unit/resources/aws_ebs_volumes_test.rb
> +    volume_id = "ebs-12345"
```suggestion
```

2021-12-29 08:35 UTC, Nirbhay1997 approved these changes
LGTM   :100:

2021-12-30 15:43 UTC, dkumaras approved these changes

2021-12-30 15:45 UTC, merged